# Project Configuration

# C++ Project
language: cpp

dist: trusty
sudo: required

# Build Job Matrix

jobs:
    include:

        # Valgrind
        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7', 'cmake', 'ninja-build', 'valgrind', 
                             'libopenblas-dev', 'liblapack-dev',
                             'libarpack2-dev', 'realpath']
          env:
              - CXX_COMPILER="g++-7"
              - CC_COMPILER="gcc-7"
              - CTEST_OPTIONS="-T memcheck"
              - VALGRIND="ON"

        # Coveralls
        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources: ['ubuntu-toolchain-r-test']
                  packages: ['g++-7', 'cmake', 'ninja-build',
                             'libopenblas-dev', 'liblapack-dev',
                             'libarpack2-dev', 'realpath']
          before_install:
              - sudo -H pip install --upgrade requests[security]
              - pip install --user cpp-coveralls
          after_success:
              - >
                coveralls 
                --root ../../ 
                --build-root ./ 
                --include include 
                --exclude lib
                --gcov 'gcov-7' 
                --gcov-options '\-lp'
          env:
              - CXX_COMPILER="g++-7"
              - CC_COMPILER="gcc-7"
              - COVERALL="ON"
              - CMAKE_OPTIONS="-DAUTOPPL_ENABLE_TEST_COVERAGE=ON"

        # Linux/GCC>=5

        - os: linux
          compiler: gcc
          env:
              - CXX_COMPILER="g++-7"
              - CC_COMPILER="gcc-7"
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-7', 'ninja-build',
                         'libopenblas-dev', 'liblapack-dev',
                         'libarpack2-dev', 'realpath']

        - os: linux
          compiler: gcc
          env: 
              - CXX_COMPILER="g++-8"
              - CC_COMPILER="gcc-8"
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-8', 'ninja-build',
                         'libopenblas-dev', 'liblapack-dev',
                         'libarpack2-dev', 'realpath']

        - os: linux
          compiler: gcc
          env: 
              - CXX_COMPILER="g++-9"
              - CC_COMPILER="gcc-9"
          addons:
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-9', 'ninja-build',
                         'libopenblas-dev', 'liblapack-dev',
                         'libarpack2-dev', 'realpath']

# Build Script

script:

    # set CXX to correct compiler
    - if [[ "${CXX_COMPILER}" != "" ]]; then
        export CXX=${CXX_COMPILER};
        export CC=${CC_COMPILER};
      fi 

    # show OS/compiler/cmake version
    - uname -a
    - ${CXX} --version
    - ${CC} --version
    - cmake --version

    # setup, clean build, and test
    - ./setup.sh
    - >
      ./clean-build.sh 
      release
      ${CMAKE_OPTIONS} 
      -DAUTOPPL_ENABLE_BENCHMARK=OFF 
      -DAUTOPPL_ENABLE_TEST=ON
    - cd build/release
    - ctest ${CTEST_OPTIONS} -j12

    # if testing valgrind
    - if [[ "${VALGRIND}" == "ON" ]]; then
        cat ./Testing/Temporary/MemoryChecker.*.log;
      fi
